name: kaen
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.7.0
  flame_forge2d: ^0.12.5
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  peanut: ^4.3.1

flutter:
  uses-material-design: true

  fonts:
    - family: DotGothic16
      fonts:
        - asset: fonts/DotGothic16-Regular.ttf

  assets:
    - assets/images/
